name: checking ${{ secrets.NAME }}

on: workflow_dispatch

jobs:
  testing-job:
    runs-on: ubuntu-latest
    steps:
      - name: checking version
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
        run: node -v
